In [ ]:
# Step 0: 安装并导入库
!pip install nashpy
!pip install quantecon

import nashpy as nash
import numpy as np

# Step 1: 定义一个函数生成 payoff matrices
def create_payoff_matrices(cap):
    """
    对每个 cap 值生成两玩家离散策略博弈 payoff matrices
    假设策略集合为: [0, 50%, 100%] 的 cap
    payoff = 提议值，如果超过对方剩余则为0
    """
    strategies = [0, cap/2, cap]  # 离散化策略集合
    n = len(strategies)

    A = np.zeros((n,n))  # Player 1 payoff
    B = np.zeros((n,n))  # Player 2 payoff

    for i, s1 in enumerate(strategies):
        for j, s2 in enumerate(strategies):
            # 简单假设 payoff = 自己得到的金额，如果 sum > cap 则按比例缩放
            total = s1 + s2
            if total <= cap:
                A[i,j] = s1
                B[i,j] = s2
            else:
                # 超过 cap 按比例缩减
                A[i,j] = s1 * cap/total
                B[i,j] = s2 * cap/total
    return A, B, strategies

# Step 2: 定义一个函数计算并显示均衡
def compute_equilibria(cap):
    print(f"\n--- Cap = {cap} ---")
    A, B, strategies = create_payoff_matrices(cap)

    # 显示 payoff matrices
    print("Player 1 payoff matrix (rows) and Player 2 payoff matrix (columns):")
    print("Player 1:")
    print(A)
    print("Player 2:")
    print(B)

    # 创建 Nash 游戏对象
    game = nash.Game(A, B)

    # 求解均衡（支持枚举法）
    equilibria = game.support_enumeration()

    # 打印均衡
    print("\nComputed equilibria (strategy probabilities for Player 1 and Player 2):")
    for eq in equilibria:
        print(eq)

    # 可选：计算对应的 expected payoffs
    for eq in equilibria:
        payoff = game[eq]
        print("Expected payoffs:", payoff)

# Step 3: 对三种 cap 分别计算
for cap in [10, 100, 1000]:
    compute_equilibria(cap)


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.7/325.7 kB 7.8 MB/s eta 0:00:00

--- Cap = 10 ---
Player 1 payoff matrix (rows) and Player 2 payoff matrix (columns):
Player 1:
[[ 0.          0.          0.        ]
 [ 5.          5.          3.33333333]
 [10.          6.66666667  5.        ]]
Player 2:
[[ 0.          5.         10.        ]
 [ 0.          5.          6.66666667]
 [ 0.          3.33333333  5.        ]]

Computed equilibria (strategy probabilities for Player 1 and Player 2):
(array([0., 0., 1.]), array([0., 0., 1.]))

--- Cap = 100 ---
Player 1 payoff matrix (rows) and Player 2 payoff matrix (columns):
Player 1:
[[  0.           0.           0.        ]
 [ 50.          50.          33.33333333]
 [100.          66.66666667  50.        ]]
Player 2:
[[  0.          50.         100.        ]
 [  0.          50.          66.66666667]
 [  0.          33.33333333  50.        ]]

Computed equilibria (strategy probabilities for Player 1 and Player 2):
(array([0., 0., 1.]), array(